### ISSUE TITLE
Error in Line 48?

### ISSUE THREAD

**Issue by giri-v** [greenwombat/sp108e#1]
Hi, I tried to use your lib and found this error while running your provided example.js. Only difference is I am using your lib as a "require".

node libtest.js
/share/web/led-strip-web/node_modules/sp108e/sp108e.js:48
  toggleOnOff = async () => {
              ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/share/web/led-strip-web/libtest.js:1:54)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

Any thoughts on what I might have wrong?

**Comment by greenwombat** [comment]
Hi @giri-v - Which version of Node are you using? I was using 12.16.2.

Lower versions may not understand async?

**Comment by giri-v** [comment]
Ummmm, where is the I'm stoopid emoji! v14.3.0 works fine. Thanks. I will fork and try to add some REST functionality.

**Comment by greenwombat** [comment]
No problem! I'd recommend using nvm to ensure you're using the right version - if you don't already.

Looking forward to seeing anything you do on your fork!
