### ISSUE TITLE
Help running on Raspberry Pi

### ISSUE THREAD

**Issue by Varguit** [greenwombat/sp108e#6]
Hi, can someone help me with this problem?

I'm trying to run this script inside a Raspberry pi but I'm getting this error:

`pi@raspberrypi:~/node_modules/sp108e $ npm run example

> sp108e@0.0.5 example /home/pi/node_modules/sp108e
> node examples/example.js

/home/pi/node_modules/sp108e/sp108e.js:48
  toggleOnOff = async () => {
              ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/node_modules/sp108e/examples/example.js:6:54)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)`

My node version is v10.23.0
My npm version is 6.14.8

**Comment by Varguit** [comment]
I found it. 
Node version has to be updated, minimum version is 12, I think (Using v14 right now and no syntax problems)
